import os
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yaml
import glob
from transformers import AutoTokenizer
from captum.attr import LayerIntegratedGradients
from models import get_model

def find_latest_checkpoint(base_dir):
    """Finds the most recent checkpoint generated by HF Trainer."""
    checkpoints = glob.glob(os.path.join(base_dir, "checkpoint-*"))
    if not checkpoints:
        return base_dir
    checkpoints.sort(key=lambda x: int(x.split("-")[-1]))
    return checkpoints[-1]

def main():
    print("🎨 Initializing Batch Heatmap Generator for Q1 Journal...")
    
    config_path = "configs/roberta_glue.yaml"
    seed = 42
    device = "cuda" if torch.cuda.is_available() else "cpu"
    
    # ---------------------------------------------------------
    # Golden Cases Configuration for the Paper
    # ---------------------------------------------------------
    eval_cases = {
        "sst2": [
            # Main Text: Clear success on positive sentiment
            {"name": "sst2_success_positive", "text1": "a visually stunning and intellectually engaging masterpiece .", "text2": None, "target": 1},
            # Main Text: Clear success on negative sentiment
            {"name": "sst2_success_negative", "text1": "a dull , lifeless , and utterly predictable mess .", "text2": None, "target": 0},
            # Appendix: Failure case showing reliance on [SEP]
            {"name": "sst2_failure_case", "text1": "it's a charming and often affecting journey .", "text2": None, "target": 1}
        ],
        "mrpc": [
            # Main Text: Discerning contradiction (rose vs fell)
            {"name": "mrpc_success_contradiction", "text1": "The stock market rose by 2 percent today .", "text2": "The stock market fell by 2 percent today .", "target": 0},
            # Appendix: Recognizing paraphrase across different structures
            {"name": "mrpc_success_entailment", "text1": "The company reported a profit of 5 million dollars .", "text2": "A 5 million dollar profit was reported by the corporation .", "target": 1}
        ]
    }
    
    methods = ["fft", "static_tada", "flex_tada", "lora"]
    display_names = ["FFT (Upper Bound)", "Baseline TADA", "Flexible-TADA", "LoRA"]
    
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    tokenizer = AutoTokenizer.from_pretrained(config["model"]["model_name_or_path"])
    os.makedirs("outputs/visualizations", exist_ok=True)

    # ---------------------------------------------------------
    # Processing Loop
    # ---------------------------------------------------------
    for task, cases in eval_cases.items():
        print(f"\n========================================")
        print(f"🚀 Processing Task: {task.upper()}")
        print(f"========================================")
        
        # Load all 4 models for the current task into memory/dict to avoid reloading
        loaded_models = {}
        for method in methods:
            print(f"📦 Loading {method.upper()} model for {task}...")
            model_dir = f"outputs/{task}_{method}_{seed}"
            ckpt_dir = find_latest_checkpoint(model_dir)
            
            model = get_model(config, method, num_labels=2, tokenizer=tokenizer)
            
            bin_path = os.path.join(ckpt_dir, "pytorch_model.bin")
            safe_path = os.path.join(ckpt_dir, "model.safetensors")
            
            if os.path.exists(bin_path):
                model.load_state_dict(torch.load(bin_path, map_location=device), strict=False)
            elif os.path.exists(safe_path):
                from safetensors.torch import load_file
                model.load_state_dict(load_file(safe_path, device=device), strict=False)
            else:
                print(f"⚠️ Warning: No trained weights found in {ckpt_dir} for {method}.")
            # ---------------------
            
            model.to(device)
            model.eval()
            loaded_models[method] = model

        # Generate heatmap for each specific case
        for case in cases:
            print(f"\n📊 Generating heatmap for: {case['name']} ...")
            
            # Prepare inputs dynamically based on whether text2 exists (SST-2 vs MRPC)
            if case["text2"] is None:
                inputs = tokenizer(case["text1"], return_tensors="pt").to(device)
            else:
                inputs = tokenizer(case["text1"], case["text2"], return_tensors="pt").to(device)
                
            input_ids = inputs["input_ids"]
            attention_mask = inputs["attention_mask"]
            actual_len = attention_mask.sum().item()
            
            # Clean tokens for professional visualization
            raw_tokens = tokenizer.convert_ids_to_tokens(input_ids[0][:actual_len])
            tokens = [t.replace('Ġ', '').replace('<s>', '[CLS]').replace('</s>', '[SEP]') for t in raw_tokens]

            heatmap_matrix = np.zeros((len(methods), actual_len))

            for row_idx, method in enumerate(methods):
                model = loaded_models[method]
                target_class = case["target"]

                def custom_forward(inputs, mask):
                    return model(input_ids=inputs, attention_mask=mask).logits

                embedding_layer = model.get_input_embeddings()
                lig = LayerIntegratedGradients(custom_forward, embedding_layer)

                baseline_ids = torch.full_like(input_ids, tokenizer.pad_token_id)
                
                with torch.enable_grad():
                    attributions = lig.attribute(
                        inputs=input_ids,
                        baselines=baseline_ids,
                        target=target_class,
                        additional_forward_args=(attention_mask,),
                        n_steps=50, 
                        return_convergence_delta=False
                    )

                token_scores = attributions.sum(dim=-1).squeeze(0).detach().cpu().numpy()[:actual_len]
                
                # Normalize scores to [-1, 1] for this row
                max_abs = np.max(np.abs(token_scores))
                if max_abs > 0:
                    token_scores = token_scores / max_abs
                    
                heatmap_matrix[row_idx, :] = token_scores

            # ---------------------------------------------------------
            # Plotting Logic
            # ---------------------------------------------------------
            # Dynamically adjust width based on sequence length to prevent squishing
            fig_width = max(12, actual_len * 0.7) 
            plt.figure(figsize=(fig_width, 3.5)) 
            
            formatted_annot = np.array([[f"{val:.2f}" for val in row] for row in heatmap_matrix])

            sns.heatmap(heatmap_matrix, annot=formatted_annot, fmt="", cmap="coolwarm", 
                        vmin=-1, vmax=1, center=0, cbar=True, 
                        xticklabels=tokens, yticklabels=display_names, 
                        annot_kws={"size": 10}, linewidths=0.5, linecolor='gray')
            
            plt.xticks(rotation=45, ha='right', fontsize=11)
            plt.yticks(rotation=0, fontsize=11, fontweight='bold')
            
            class_str = "Positive" if target_class == 1 else "Negative"
            plt.title(f"Integrated Gradients Attribution ({task.upper()})\nTarget Class: {class_str} | Case: {case['name'].replace('_', ' ').title()}", 
                      pad=15, fontsize=14, fontweight='bold')
            
            save_path = f"outputs/visualizations/{case['name']}.png"
            plt.savefig(save_path, bbox_inches='tight', dpi=300)
            plt.close()
            print(f"✅ Saved: {save_path}")

    print("\n🎉 All heatmaps generated successfully!")

if __name__ == "__main__":
    main()